apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: ecommerce
data:
  init.sql: |
    CREATE USER products_user WITH PASSWORD 'products_pass';
    CREATE USER orders_user   WITH PASSWORD 'orders_pass';
    CREATE USER users_user    WITH PASSWORD 'users_pass';

    CREATE DATABASE products_db OWNER products_user;
    CREATE DATABASE orders_db   OWNER orders_user;
    CREATE DATABASE users_db    OWNER users_user;

    REVOKE CONNECT ON DATABASE products_db FROM PUBLIC;
    REVOKE CONNECT ON DATABASE orders_db   FROM PUBLIC;
    REVOKE CONNECT ON DATABASE users_db    FROM PUBLIC;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: admin_pass
          volumeMounts:
            - name: init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecommerce
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
