apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_PASSWORD: "admin_pass"
  PRODUCTS_DB_PASSWORD: "products_pass"
  ORDERS_DB_PASSWORD: "orders_pass"
  USERS_DB_PASSWORD: "users_pass"