name: orders-service
image:
  repository: mv7moud/ecommerce-orders-service
  tag: "a81b9ee0164f059348c37daec76d2f5cc6799c9e"
db:
  name: orders_db
  user: orders_user
  passwordKey: ORDERS_DB_PASSWORD
extraEnv:
  - name: PRODUCTS_SERVICE_URL
    value: http://products-service:3000
  - name: USERS_SERVICE_URL
    value: http://users-service:3000