name: orders-service
image:
  repository: mv7moud/ecommerce-orders-service
  tag: "f3525cbd11c8098eb99c48ffda7085cfc3e53207"
db:
  name: orders_db
  user: orders_user
  passwordKey: ORDERS_DB_PASSWORD
extraEnv:
  - name: PRODUCTS_SERVICE_URL
    value: http://products-service:3000
  - name: USERS_SERVICE_URL
    value: http://users-service:3000