name: orders-service
image:
  repository: mv7moud/ecommerce-orders-service
  tag: "efb2e901a0270e2741bad5020363a2705c5a6103"
db:
  name: orders_db
  user: orders_user
  passwordKey: ORDERS_DB_PASSWORD
extraEnv:
  - name: PRODUCTS_SERVICE_URL
    value: http://products-service:3000
  - name: USERS_SERVICE_URL
    value: http://users-service:3000