name: products-service
image:
  repository: mv7moud/ecommerce-products-service
  tag: "90bf43f6d9cba9d3c275557843c861647a938b9c"
db:
  name: products_db
  user: products_user
  passwordKey: PRODUCTS_DB_PASSWORD
probes:
  enabled: true