name: products-service
image:
  repository: mv7moud/ecommerce-products-service
  tag: 52907d4f9dd61cb5ddec29f5f58db89fcb9f3a54
db:
  name: products_db
  user: products_user
  passwordKey: PRODUCTS_DB_PASSWORD
probes:
  enabled: true