name: products-service
image:
  repository: mv7moud/ecommerce-products-service
  tag: "a81b9ee0164f059348c37daec76d2f5cc6799c9e"
db:
  name: products_db
  user: products_user
  passwordKey: PRODUCTS_DB_PASSWORD
probes:
  enabled: true